# -*- coding: utf-8 -*-
"""UnlockThePIN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xV4QjiKGrp_sGuo3Z3so8OVY_IRc6tD7
"""

import random
import os

LEADERBOARD_CSV_FILE = 'pin_game_results.csv'

def generatePIN(pin_length):
  # Generate a random PIN of specified length
  return ''.join(random.choices('0123456789', k=pin_length))

def get_guess(pin_length):
  while True:
    try:
      guess = input(f"Guess the PIN ({pin_length} digits): ")
      if len(guess) != pin_length or not guess.isdigit():
        raise ValueError
      return guess
    except ValueError:
      print(f"Invalid input. Please enter a {pin_length}-digit number")

def comparePinAndGuess(guess_num, pin_num, user_name, attempts):
  if guess_num == pin_num:
    print(f"Congratulations {user_name}, you guessed it in {attempts} attempts!!")
    return True
  else:
    feedback = []
    for i in range(len(guess_num)):
      if guess_num[i] == pin_num[i]:
        feedback.append(f"Digit {i+1} is correct")
      else:
        feedback.append(f"Digit {i+1} is incorrect")
    print("\n".join(feedback))
    print(f"{user_name}, you guessed it wrong. Try again!")
    return False

def ask_difficulty():
  while True:
    difficulty = input("Choose difficulty (Easy: 4 digits, Medium: 6 digits, Hard: 8 digits): ").lower()
    if difficulty == 'easy':
      return 4
    elif difficulty == 'medium':
      return 6
    elif difficulty == 'hard':
      return 8
    else:
      print("Invalid difficulty. Please choose 'Easy', 'Medium', or 'Hard'.")

# --- Leaderboard functions ---
def save_game_results(player_name, pin, attempts):
  try:
    # Check if the CSV file exists
    file_exists = os.path.exists(LEADERBOARD_CSV_FILE)

    with open(LEADERBOARD_CSV_FILE, 'a') as f:
      if not file_exists:
        # Write header only if the file is new
        f.write("PlayerName,PIN,Attempts\n")
      f.write(f"{player_name},{pin},{attempts}\n")
    print("Game results saved to pin_game_results.csv")
  except Exception as e:
    print(f"An error occurred while saving game results: {e}")

def display_top_five_wins():
  if not os.path.exists(LEADERBOARD_CSV_FILE):
    print("No game results available yet.")
    return

  results = []
  try:
    with open(LEADERBOARD_CSV_FILE, 'r') as f:
      # Skip header
      next(f) # Assumes header is always present after save_game_results is called once
      for line in f:
        parts = line.strip().split(',')
        if len(parts) == 3:
          player_name, pin_str, attempts_str = parts
          results.append((player_name, int(attempts_str)))
  except Exception as e:
    print(f"An error occurred while reading game results: {e}")
    return

  # Sort by attempts (ascending) to find the fastest wins
  results.sort(key=lambda x: x[1])

  # Get unique player names and their best scores
  best_scores_map = {}
  for player, attempts in results:
    if player not in best_scores_map or attempts < best_scores_map[player]:
      best_scores_map[player] = attempts

  # Convert to list of tuples and sort again
  best_scores = sorted([(player, score) for player, score in best_scores_map.items()], key=lambda x: x[1])

  print("\n--- Top 5 Fastest Wins ---")
  if best_scores:
    for i, (player, attempts) in enumerate(best_scores[:5]):
      print(f"{i + 1}. {player} - {attempts} attempts")
  else:
    print("No top scores to display.")
  print("--------------------------")
# --- End of Leaderboard functions ---


# Main execution
user_name = input("Enter your name: ")

while True: # Outer loop for playing multiple games
  pin_length = ask_difficulty() # Get difficulty from user
  pin = generatePIN(pin_length)
  print(f"Hello {user_name}! I have generated a {pin_length}-digit PIN. Can you guess it?")

  attempts = 0
  while True:
    attempts += 1
    guess = get_guess(pin_length) # Pass pin_length to get_guess
    if comparePinAndGuess(guess, pin, user_name, attempts):
      save_game_results(user_name, pin, attempts) # Save results upon winning
      display_top_five_wins() # Display top wins after game ends
      break # Break from inner game loop

  play_again = input("Do you want to play again? (yes/no): ").lower()
  if play_again != 'yes':
    print("Thanks for playing!")
    break # Break from outer loop if user doesn't want to play again